[package]
name = "inf_4101c"
version = "0.0.1"
authors = ["RÃ©mi Nicole"]
license = "MIT"

[dependencies]
rscam = "0.5.0"
piston_window = "0.57.0"
image = "0.10.0"
gfx_device_gl = "*"
docopt = "0.6"
rustc-serialize = "0.3"
